### ISSUE TITLE
Invalid expression &cpo^M

### ISSUE THREAD

**Issue by scrouthtv** [chrisbra/DynamicSigns#3]
I am running neovim with vim-plug, both newest version, and tried installing this plugin.
I didn't configure anything, simply installed it and got this error:

```
Error detected while processing /home/x/.vim/plugged/DynamicSigns/plugin/SignsPlugin.vim:
line   16:
E15: Invalid expression: &cpo^M
line   17:
E15: Invalid expression: exists("g:loaded_Signs") || &cp^M
line   71:
E488: Trailing characters
line   73:
E171: Missing :endif
```

**Comment by chrisbra** [comment]
What neovim version is this? I don't see anything wrong with the Code. Can you test a newer version?

**Comment by scrouthtv** [comment]
The problem was that I somehow got Windows file endings in this file even though I am on linux.. Thanks for the help nevertheless :/
