### ISSUE TITLE
Try to set relative number but nothing happens in neovim

### ISSUE THREAD

**Issue by longguzzz** [chrisbra/DynamicSigns#5]
I am trying your method of setting relativenumber beside line number.
[How can I set number and relativenumber at the same time?](https://vi.stackexchange.com/questions/5680/how-can-i-set-number-and-relativenumber-at-the-same-time)
And I install DynamicSigns successfully, whose commands are shown in completion.

Then I embed `CustomSignExpression` using following code in neovim.
```
vim.api.nvim_exec([[
fu! CustomSignExpression(lnum, div)
if a:lnum < line('w0') || a:lnum > line ('w$')
    return 0
endif
if !exists("#CustomSignExpression#CursorMoved")
    augroup CustomSignExpression
        au!
        au CursorMoved * :Signs
        au VimResized  * :UpdateSigns
    augroup end
endif
let part=abs(a:lnum - line('.'))
if part % a:div == 0
    return part > 99 ? 99 : part
else
    return 0
endif
endfu
]],false)
```

But it seems that `:Signs` and `:SignExpression CustomSignExpression(v:lnum, 5)` don't work.

**Comment by chrisbra** [comment]
have you tried it without the lua stuff? 

I have basically no idea how this is supposed to work with lua.

**Comment by longguzzz** [comment]
No. Because I am less familiar with vim. 
Although this problem reserves, I find myself being used to locating with absolute line number in these days😂. Maybe this issue can be closed.

**Comment by chrisbra** [comment]
let me then close it
